# 开发环境配置
spring:
  thymeleaf:
    cache: false
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: bzj
          password: BoZhongJi123
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/bzj?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true&useSSL=false
file:
  #文件上传目录 绝对路径 末尾不需要加 /
  path: D:/files #windows
  #path: /data/files #linux
